SiriusDepositsDetectorJob:
  Db:
    LogsConnString:
      settings-key: SiriusDepositsDetectorJob-LogsConnString
      types: [ AzureTableStorage ]
    DataConnString:
      settings-key: SiriusDepositsDetectorJob-DataConnString
      types: [ AzureTableStorage ]
  Cqrs:
    RabbitConnectionString:
      settings-key: RabbitSagas
      types: [ RabbitMq ]
SlackNotifications:
  AzureQueue:
    ConnectionString:
      settings-key: SlackNotificationsConnString
      types: [ AzureTableStorage ]
    QueueName:
      settings-key: SlackQueueName
MonitoringServiceClient:
  MonitoringServiceUrl:
    settings-key: MonitoringServiceUrl
SiriusApiServiceClient:
  GrpcServiceUrl:
    settings-key: SiriusApi-ServiceUrl
  ApiKey:
    settings-key: SiriusApi-DepositDetector-ApiKey
  BrokerAccountId:
    settings-key: SiriusApi-BrokerAccountId
MatchingEngineClient:
  IpEndpoint:
    Port:
      settings-key: MatchingEngine-Port
    Host:
      settings-key: MatchingEngine-Host
AssetsServiceClient:
  ServiceUrl:
    settings-key: AssetsServiceUrl
  ExpirationPeriod:
    settings-key: AssetsServiceExpirationPeriod
